/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "OE_aliases.h"
#include "OE.h"
#include "CLK_aliases.h"
#include "CLK.h"
#include "LAT_aliases.h"
#include "LAT.h"
#include "D_aliases.h"
#include "D.h"
#include "C_aliases.h"
#include "C.h"
#include "B_aliases.h"
#include "B.h"
#include "A_aliases.h"
#include "A.h"
#include "B2_aliases.h"
#include "B2.h"
#include "G2_aliases.h"
#include "G2.h"
#include "R2_aliases.h"
#include "R2.h"
#include "B1_aliases.h"
#include "B1.h"
#include "G1_aliases.h"
#include "G1.h"
#include "R1_aliases.h"
#include "R1.h"
#include "UART.h"
#include "rx_isr.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

